version: '3'

services:
  app:
    image: app
    build: ./app
    volumes:
      - ./app/src:/opt/app/src
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601

volumes:
  esdata: